plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/shihaoran/prime-day-review/prime-day-review-hugo/public"
publishOrigin = "config"
commandOrigin = "config"
command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.160.1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]