name: Deploy Hugo Site

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HUGO_VERSION: 0.160.1
  VERCEL_ORG_ID: team_Hm4fGPnoIEW1egi6MsTfcLav
  VERCEL_PROJECT_ID: prj_GT3Bi9BJyWksayDZDTd6KDxp4F3K

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Hugo Build
        run: hugo --gc --minify
        working-directory: ./

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
